config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'home#index'

  resources :banks do
  	resources :comments
  end
  devise_for :users, controllers: { registrations: "registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank.rb
class Bank < ApplicationRecord
	belongs_to :user
	has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :bank
end

app/models/user.rb
class User < ApplicationRecord
	has_many :banks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  before_action :set_bank, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!
  # GET /banks
  # GET /banks.json
  def index
    @banks = Bank.all
  end

  # GET /banks/1
  # GET /banks/1.json
  def show
  end

  # GET /banks/new
  def new
    @bank = Bank.new
  end

  # GET /banks/1/edit
  def edit
  end

  # POST /banks
  # POST /banks.json
  def create
    @user = current_user

    @bank =  @user.banks.new(bank_params)

    respond_to do |format|
      if @bank.save

        BankMailer.bank_created(@user).deliver
        format.html { redirect_to @bank, notice: 'Bank was successfully created.' }
        format.json { render :show, status: :created, location: @bank }
      else
        format.html { render :new }
        format.json { render json: @bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /banks/1
  # PATCH/PUT /banks/1.json
  def update
    respond_to do |format|
      if @bank.update(bank_params)
        format.html { redirect_to @bank, notice: 'Bank was successfully updated.' }
        format.json { render :show, status: :ok, location: @bank }
      else
        format.html { render :edit }
        format.json { render json: @bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banks/1
  # DELETE /banks/1.json
  def destroy
    @bank.destroy
    respond_to do |format|
      format.html { redirect_to banks_url, notice: 'Bank was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank
      @bank = Bank.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bank_params
      params.require(:bank).permit(:PostDate, :BankName, :PostName, :Qualification, :LastDate, :Description, :Qualification_desc, :TotalPost, :AgeLimit, :SelectionProcess, :ApplicationFees, :ApplyLink, :LastDate, :LastDateOnlineApplication, :CallLetter, :CallLetterLink, :DateofExam, :HowtoApply, :OfficialNotification)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@bank = Bank.find(params[:bank_id])
		@comment = @bank.comments.create(comments_params)

		CommentMailer.comment_created(current_user,@bank.user,@comment.content).deliver
		redirect_to bank_path(@bank)
	end
	private
	def comments_params
		params.require(:comment).permit(:content)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	# user_signed_in?
  	redirect_to banks_path
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	private
	def sign_up_params
		params.require(:user).permit(:name, :email, :password, :password_confiramation)
	end
	def account_update_params
		params.require(:user).permit(:name, :email, :password, :password_confiramation, :current_password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/banks/_form.html.erb
<%= form_for(bank) do |f| %>
  <% if bank.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bank.errors.count, "error") %> prohibited this bank from being saved:</h2>

      <ul>
      <% bank.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :PostDate %>
    <%= f.date_select :PostDate %>
  </div>

  <div class="field">
    <%= f.label :BankName %>
    <%= f.text_field :BankName %>
  </div>

  <div class="field">
    <%= f.label :PostName %>
    <%= f.text_field :PostName %>
  </div>

  <div class="field">
    <%= f.label :Qualification %>
    <%= f.text_field :Qualification %>
  </div>

  <div class="field">
    <%= f.label :LastDate %>
    <%= f.date_select :LastDate %>
  </div>

  <div class="field">
    <%= f.label :Description %>
    <%= f.text_area :Description %>
  </div>

  <div class="field">
    <%= f.label :Qualification_desc %>
    <%= f.text_area :Qualification_desc %>
  </div>

  <div class="field">
    <%= f.label :TotalPost %>
    <%= f.number_field :TotalPost %>
  </div>

  <div class="field">
    <%= f.label :AgeLimit %>
    <%= f.text_area :AgeLimit %>
  </div>

  <div class="field">
    <%= f.label :SelectionProcess %>
    <%= f.text_area :SelectionProcess %>
  </div>

  <div class="field">
    <%= f.label :ApplicationFees %>
    <%= f.text_area :ApplicationFees %>
  </div>

  <div class="field">
    <%= f.label :ApplyLink %>
    <%= f.text_area :ApplyLink %>
  </div>

  <div class="field">
    <%= f.label :LastDate %>
    <%= f.date_select :LastDate %>
  </div>

  <div class="field">
    <%= f.label :LastDateOnlineApplication %>
    <%= f.date_select :LastDateOnlineApplication %>
  </div>

  <div class="field">
    <%= f.label :CallLetter %>
    <%= f.text_area :CallLetter %>
  </div>

  <div class="field">
    <%= f.label :CallLetterLink %>
    <%= f.text_area :CallLetterLink %>
  </div>

  <div class="field">
    <%= f.label :DateofExam %>
    <%= f.date_select :DateofExam %>
  </div>

  <div class="field">
    <%= f.label :HowtoApply %>
    <%= f.text_area :HowtoApply %>
  </div>

  <div class="field">
    <%= f.label :OfficialNotification %>
    <%= f.text_area :OfficialNotification %>
  </div>
<div class="field">
    <%= f.label :user %>
    <%= f.number_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/banks/edit.html.erb
<h1>Editing Bank</h1>

<%= render 'form', bank: @bank %>

<%= link_to 'Show', @bank %> |
<%= link_to 'Back', banks_path %>

app/views/banks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Banks</h1>

<table>
  <thead>
    <tr>
      <th>Postdate</th>
      <th>Bankname</th>
      <th>Postname</th>
      <th>Qualification</th>
      <th>Lastdate</th>
      <th>Description</th>
      <th>Qualification desc</th>
      <th>Totalpost</th>
      <th>Agelimit</th>
      <th>Selectionprocess</th>
      <th>Applicationfees</th>
      <th>Applylink</th>
      <th>Lastdate</th>
      <th>Lastdateonlineapplication</th>
      <th>Callletter</th>
      <th>Callletterlink</th>
      <th>Dateofexam</th>
      <th>Howtoapply</th>
      <th>Officialnotification</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @banks.each do |bank| %>
      <tr>
        <td><%= bank.PostDate %></td>
        <td><%= bank.BankName %></td>
        <td><%= bank.PostName %></td>
        <td><%= bank.Qualification %></td>
        <td><%= bank.LastDate %></td>
        <td><%= bank.Description %></td>
        <td><%= bank.Qualification_desc %></td>
        <td><%= bank.TotalPost %></td>
        <td><%= bank.AgeLimit %></td>
        <td><%= bank.SelectionProcess %></td>
        <td><%= bank.ApplicationFees %></td>
        <td><%= bank.ApplyLink %></td>
        <td><%= bank.LastDate %></td>
        <td><%= bank.LastDateOnlineApplication %></td>
        <td><%= bank.CallLetter %></td>
        <td><%= bank.CallLetterLink %></td>
        <td><%= bank.DateofExam %></td>
        <td><%= bank.HowtoApply %></td>
        <td><%= bank.OfficialNotification %></td>
        <td><%= link_to 'Show', bank %></td>
        <td><%= link_to 'Edit', edit_bank_path(bank) %></td>
        <td><%= link_to 'Destroy', bank, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bank', new_bank_path %>

app/views/banks/new.html.erb
<h1>New Bank</h1>

<%= render 'form', bank: @bank %>

<%= link_to 'Back', banks_path %>

app/views/banks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Postdate:</strong>
  <%= @bank.PostDate %>
</p>

<p>
  <strong>Bankname:</strong>
  <%= @bank.BankName %>
</p>

<p>
  <strong>Postname:</strong>
  <%= @bank.PostName %>
</p>

<p>
  <strong>Qualification:</strong>
  <%= @bank.Qualification %>
</p>

<p>
  <strong>Lastdate:</strong>
  <%= @bank.LastDate %>
</p>

<p>
  <strong>Description:</strong>
  <%= @bank.Description %>
</p>

<p>
  <strong>Qualification desc:</strong>
  <%= @bank.Qualification_desc %>
</p>

<p>
  <strong>Totalpost:</strong>
  <%= @bank.TotalPost %>
</p>

<p>
  <strong>Agelimit:</strong>
  <%= @bank.AgeLimit %>
</p>

<p>
  <strong>Selectionprocess:</strong>
  <%= @bank.SelectionProcess %>
</p>

<p>
  <strong>Applicationfees:</strong>
  <%= @bank.ApplicationFees %>
</p>

<p>
  <strong>Applylink:</strong>
  <%= @bank.ApplyLink %>
</p>

<p>
  <strong>Lastdate:</strong>
  <%= @bank.LastDate %>
</p>

<p>
  <strong>Lastdateonlineapplication:</strong>
  <%= @bank.LastDateOnlineApplication %>
</p>

<p>
  <strong>Callletter:</strong>
  <%= @bank.CallLetter %>
</p>

<p>
  <strong>Callletterlink:</strong>
  <%= @bank.CallLetterLink %>
</p>

<p>
  <strong>Dateofexam:</strong>
  <%= @bank.DateofExam %>
</p>

<p>
  <strong>Howtoapply:</strong>
  <%= @bank.HowtoApply %>
</p>

<p>
  <strong>Officialnotification:</strong>
  <%= @bank.OfficialNotification %>
</p>
<p>
  <strong>User:</strong>
  <%= @bank.user_id %>
</p>
<h2>Comments</h2>
<%=  render @bank.comments %>
<br>
<%= render "comments/form"%>
<%= link_to 'Edit', edit_bank_path(@bank) %> |
<%= link_to 'Back', banks_path %>

app/views/comments/_comment.html.erb
<p><%= comment.content %></p>

app/views/comments/_form.html.erb
<%= form_for([@bank, @bank.comments.build]) do |f| %>
<div class="field">
	<%= f.label :content %><br>
	<%= f.text_area :content %>
</div>
<div class="actions">
	<%= f.submit %>
</div>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyMailApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
  	<% if user_signed_in? %>
  	<p>Hello, <%= current_user.name %> - <%= link_to "sign out", destroy_user_session_path, :method => 'delete' %></p>
  	<% else %>
  	<%= link_to "sign In", new_user_session_path %>
  	<%= link_to "Register", new_user_registration_path %>
  	<% end %>
    <%= yield %>
  </body>
</html>